safe: true

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: COMMON BLOG
description: COMMON BLOG FOR TECHY
baseurl: ""
url: "http://himsel.me" # replace by your site's url
twitter_username: your-name
github_username:  slkrthika # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "slkrthika ,Sriramsds"
address: "Chennai<br>India".
email: "sriramsds98@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
